block_info = [
  {
      'name': 'Student No',
      'type': 'STUDENT_NO',
      'marking_direction': 'V',
      'items': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
      'x': 69,
      'y': 338,
      'width': 376,
      'height': 280,
      'num_of_question': 8,
      'num_of_selection': 10,
      'selection_starting_number': 0,
      'Item_type': 'combo'
  },
  {
      'name': 'Test Type',
      'type': 'TEST_TYPE',
      'marking_direction': 'V',
      'items': ['Entrance', 'Selective_Trial_Test', 'Scholarship_Test', 'OC_Trial_Test', 'Class_Test', 'DUMMY', 'Blended_OCTT', 'Blended_STT'],
      'x': 441,
      'y': 350,
      'width': 38,
      'height': 236,
      'num_of_question': 1,
      'num_of_selection': 8,
      'selection_starting_number': 0,
      'Item_type': 'combo'
  },
  {
      'name': 'Test Subj',
      'type': 'SUBJECT',
      'marking_direction': 'V',
      'items': ['Maths', 'GA', 'Reading', 'Voca', 'TextType', 'Part1', 'Part2', 'Science', 'Others'],
      'x': 601,
      'y': 350,
      'width': 36,
      'height': 261,
      'num_of_question': 1,
      'num_of_selection': 9,
      'selection_starting_number': 0,
      'Item_type': 'multi'
  },
  {
      'name': 'Test Level1',
      'type': 'TEST_LEVEL1',
      'marking_direction': 'V',
      'items': ['Year1', 'Year2', 'Year3', 'Year4', 'Year5', 'Year6'],
      'x': 685,
      'y': 350,
      'width': 27,
      'height': 176,
      'num_of_question': 1,
      'num_of_selection': 6,
      'selection_starting_number': 0,
      'Item_type': 'combo'
  },
  {
      'name': 'Test Level2',
      'type': 'TEST_LEVEL2',
      'marking_direction': 'V',
      'items': ['Year7', 'Year8', 'Year9', 'Year10', 'Year11', 'Year12'],
      'x': 767,
      'y': 350,
      'width': 27,
      'height': 176,
      'num_of_question': 1,
      'num_of_selection': 6,
      'selection_starting_number': 0,
      'Item_type': 'combo'
  },
  {
      'name': 'Test No',
      'type': 'TEST_NO',
      'marking_direction': 'V',
      'items': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
      'x': 854,
      'y': 350,
      'width': 82,
      'height': 265,
      'num_of_question': 2,
      'num_of_selection': 10,
      'selection_starting_number': 0,
      'Item_type': 'num'
  },
  {
      'name': 'Branch No',
      'type': 'BRANCH_NO',
      'marking_direction': 'V',
      'items': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
      'x': 952,
      'y': 350,
      'width': 82,
      'height': 265,
      'num_of_question': 2,
      'num_of_selection': 10,
      'selection_starting_number': 0,
      'Item_type': 'num'
  },
  {
      'name': 'Answer_1',
      'type': 'ANSWER',
      'marking_direction': 'H',
      'Group': 'Math',
      'StartingQuestion': '1',
      'items': ['1', '2', '3', '4', '5'],
      'x': 131,
      'y': 675,
      'width': 175,
      'height': 410,
      'num_of_question': 15,
      'num_of_selection': 5,
      'selection_starting_number': 1,
      'Item_type': 'num'
  },
  {
      'name': 'Answer_2',
      'type': 'ANSWER',
      'marking_direction': 'H',
      'Group': 'Math',
      'StartingQuestion': '16',
      'items': ['1', '2', '3', '4', '5'],
      'x': 372,
      'y': 675,
      'width': 175,
      'height': 410,
      'num_of_question': 15,
      'num_of_selection': 5,
      'selection_starting_number': 1,
      'Item_type': 'num'
  },
  {
      'name': 'Answer_3',
      'type': 'ANSWER',
      'marking_direction': 'H',
      'Group': 'Math',
      'StartingQuestion': '31',
      'items': ['1', '2', '3', '4', '5'],
      'x': 612,
      'y': 675,
      'width': 175,
      'height': 410,
      'num_of_question': 15,
      'num_of_selection': 5,
      'selection_starting_number': 1,
      'Item_type': 'num'
  },
  {
      'name': 'Answer_4',
      'type': 'ANSWER',
      'marking_direction': 'H',
      'Group': 'Math',
      'StartingQuestion': '46',
      'items': ['1', '2', '3', '4', '5'],
      'x': 852,
      'y': 675,
      'width': 175,
      'height': 410,
      'num_of_question': 15,
      'num_of_selection': 5,
      'selection_starting_number': 1,
      'Item_type': 'num'
  },
  {
      'name': 'Answer_5',
      'type': 'ANSWER',
      'marking_direction': 'H',
      'Group': 'Thinking_Skills',
      'StartingQuestion': '1',
      'items': ['1', '2', '3', '4'],
      'x': 131,
      'y': 1143,
      'width': 175,
      'height': 410,
      'num_of_question': 15,
      'num_of_selection': 4,
      'selection_starting_number': 1,
      'Item_type': 'num'
  },
  {
      'name': 'Answer_6',
      'type': 'ANSWER',
      'marking_direction': 'H',
      'Group': 'Thinking_Skills',
      'StartingQuestion': '16',
      'items': ['1', '2', '3', '4'],
      'x': 372,
      'y': 1143,
      'width': 175,
      'height': 410,
      'num_of_question': 15,
      'num_of_selection': 4,
      'selection_starting_number': 1,
      'Item_type': 'num'
  },
  {
      'name': 'Answer_7',
      'type': 'ANSWER',
      'marking_direction': 'H',
      'Group': 'Thinking_Skills',
      'StartingQuestion': '31',
      'items': ['1', '2', '3', '4'],
      'x': 612,
      'y': 1143,
      'width': 175,
      'height': 410,
      'num_of_question': 15,
      'num_of_selection': 4,
      'selection_starting_number': 1,
      'Item_type': 'num'
  },
  {
      'name': 'Answer_8',
      'type': 'ANSWER',
      'marking_direction': 'H',
      'Group': 'Thinking_Skills',
      'StartingQuestion': '46',
      'items': ['1', '2', '3', '4'],
      'x': 852,
      'y': 1143,
      'width': 175,
      'height': 410,
      'num_of_question': 15,
      'num_of_selection': 4,
      'selection_starting_number': 1,
      'Item_type': 'num'
  },
]