sel_MT_block_data = {
    'name': 'MT_block_info',
    'pageDimensions': [1169, 1654],
    'bubbleDimensions': [18, 18],
    'preProcessors': [
        {
          "name": "GaussianBlur",
          "options": {
            "kSize": [3, 3],
            "sigmaX": 0
          }
        }
      ],
    'fieldBlocks': {
      'Student_No': {
          'name': 'Student No',
          'type': 'STUDENT_NO',
          'marking_direction': 'V',
          'items': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
          'origin': [81, 350],
          'width': 376,
          'height': 280,
          'bubblesGap': 27,
          "labelsGap": 44.5,
          'num_of_question': 8,
          'num_of_selection': 10,
          'selection_starting_number': 0,
          'Item_type': 'combo'
      },
      'Test_Type': {
          'name': 'Test Type',
          'type': 'TEST_TYPE',
          'marking_direction': 'V',
          'items': ['Entrance', 'Selective_Trial_Test', 'Scholarship_Test', 'OC_Trial_Test', 'Class_Test'],
          'origin': [451, 350],
          'width': 38,
          'height': 236,
          'bubblesGap': 27.5,
          'labelsGap': 27,
          'num_of_question': 1,
          'num_of_selection': 5,
          'selection_starting_number': 0,
          'Item_type': 'combo'
      },
      'Test_Subject': {
          'name': 'Test Subj',
          'type': 'SUBJECT',
          'marking_direction': 'V',
          'items': ['Maths', 'Thinking', 'Reading', 'Voca', 'TextType', 'Extra_TS', 'GA_Prac', 'Science', 'Others'],
          'origin': [593, 350],
          'width': 36,
          'height': 261,
          'bubblesGap': 27.5,
          'labelsGap': 27,
          'num_of_question': 1,
          'num_of_selection': 9,
          'selection_starting_number': 0,
          'Item_type': 'multi'
      },
      'Test_Level1': {
          'name': 'Test Level1',
          'type': 'TEST_LEVEL1',
          'marking_direction': 'V',
          'items': ['Year1', 'Year2', 'Year3', 'Year4', 'Year5', 'Year6'],
          'origin': [690, 350],
          'width': 27,
          'height': 176,
          'bubblesGap': 27.5,
          'labelsGap': 30,
          'num_of_question': 1,
          'num_of_selection': 6,
          'selection_starting_number': 0,
          'Item_type': 'combo'
      },
      'Test_Level2': {
          'name': 'Test Level2',
          'type': 'TEST_LEVEL2',
          'marking_direction': 'V',
          'items': ['Year7', 'Year8', 'Year9', 'Year10', 'Year11', 'Year12'],
          'origin': [767, 350],
          'width': 27,
          'height': 176,
          'bubblesGap': 27.5,
          'labelsGap': 30,
          'num_of_question': 1,
          'num_of_selection': 6,
          'selection_starting_number': 0,
          'Item_type': 'combo'
      },
      'Test_No': {
          'name': 'Test No',
          'type': 'TEST_NO',
          'marking_direction': 'V',
          'items': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
          'origin': [863, 354],
          'width': 82,
          'height': 265,
          'bubblesGap': 27,
          'labelsGap': 40.5,
          'num_of_question': 2,
          'num_of_selection': 10,
          'selection_starting_number': 0,
          'Item_type': 'num'
      },
      'Branch_No': {
          'name': 'Branch No',
          'type': 'BRANCH_NO',
          'marking_direction': 'V',
          'items': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
          'origin': [962, 354],
          'width': 82,
          'height': 265,
          'bubblesGap': 27,
          'labelsGap': 40.5,
          'num_of_question': 2,
          'num_of_selection': 10,
          'selection_starting_number': 0,
          'Item_type': 'num'
      },
      'Math_Answer_1':{
          'name': 'M_Answer_1',
          'type': 'ANSWER',
          'marking_direction': 'H',
          'Group': 'Math',
          'StartingQuestion': '1',
          'EndingQuestion': '15',
          'items': ['1', '2', '3', '4', '5'],
          'origin': [140, 679],
          'width': 175,
          'height': 410,
          'bubblesGap': 34,
          'labelsGap': 27,
          'num_of_question': 15,
          'num_of_selection': 5,
          'selection_starting_number': 1,
          'Item_type': 'num'
      },
      'Math_Answer_16': {
          'name': 'M_Answer_16',
          'type': 'ANSWER',
          'marking_direction': 'H',
          'Group': 'Math',
          'StartingQuestion': '16',
          'EndingQuestion': '30',
          'items': ['1', '2', '3', '4', '5'],
          'origin': [379, 680],
          'width': 175,
          'height': 410,
          'bubblesGap': 34,
          'labelsGap': 27,
          'num_of_question': 15,
          'num_of_selection': 5,
          'selection_starting_number': 1,
          'Item_type': 'num'
      },
      'Math_Answer_31': {
          'name': 'M_Answer_31',
          'type': 'ANSWER',
          'marking_direction': 'H',
          'Group': 'Math',
          'StartingQuestion': '31',
          'EndingQuestion': '35',
          'items': ['1', '2', '3', '4', '5'],
          'origin': [622, 680],
          'width': 175,
          'height': 410,
          'bubblesGap': 34,
          'labelsGap': 27,
          'num_of_question': 15,
          'num_of_selection': 5,
          'selection_starting_number': 1,
          'Item_type': 'num'
      },
      'Think_Answer_1':{
          'name': 'T_Answer_1',
          'type': 'ANSWER',
          'marking_direction': 'H',
          'Group': 'Thinking_Skills',
          'StartingQuestion': '1',
          'EndingQuestion': '15',
          'items': ['1', '2', '3', '4'],
          'origin': [140, 1148],
          'width': 175,
          'height': 410,
          'bubblesGap': 43.5,
          'labelsGap': 27,
          'num_of_question': 15,
          'num_of_selection': 4,
          'selection_starting_number': 1,
          'Item_type': 'num'
      },
      'Think_Answer_16':{
          'name': 'T_Answer_16',
          'type': 'ANSWER',
          'marking_direction': 'H',
          'Group': 'Thinking_Skills',
          'StartingQuestion': '16',
          'EndingQuestion': '30',
          'items': ['1', '2', '3', '4'],
          'origin': [380, 1148],
          'width': 175,
          'height': 410,
          'bubblesGap': 43.5,
          'labelsGap': 27,
          'num_of_question': 15,
          'num_of_selection': 4,
          'selection_starting_number': 1,
          'Item_type': 'num'
      },
      'Think_Answer_31':{
          'name': 'T_Answer_31',
          'type': 'ANSWER',
          'marking_direction': 'H',
          'Group': 'Thinking_Skills',
          'StartingQuestion': '31',
          'EndingQuestion': '40',
          'items': ['1', '2', '3', '4'],
          'origin': [621, 1149],
          'width': 175,
          'height': 410,
          'bubblesGap': 43.5,
          'labelsGap': 27,
          'num_of_question': 15,
          'num_of_selection': 4,
          'selection_starting_number': 1,
          'Item_type': 'num'
      },
    }
}